INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (4, "Непосредственно перед поворотом или разворотом", 4, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (5, "Заблаговременно до начала выполнения маневра", 4, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (6, " По своему усмотрению", 4, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (7, "Непосредственно перед началом маневра", 5, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (8, "Только после окончания маневра", 5, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (9, "Подать звуковой сигнал", 6, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (10, " Включить аварийную сигнализацию", 6, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (11, "Прибегнуть к помощи других лиц", 6, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (12, "Непосредственно перед началом маневра", 7, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (13, " Сразу же после завершения маневра", 7, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (14, "В процессе выполнения маневра", 7, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (15, " На перекрестках", 8, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (16, "На дорогах с односторонним движением", 8, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (17, "На пешеходных переходах", 8, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (18, " В местах остановок маршрутных транспортных средств", 8, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (19, "Да", 9, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (20, "Нет", 9, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (21, "Да, только при наличии в непосредственной близости пешеходов", 9, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (22, "Да", 10, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (23, "Нет", 10, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (24, " Да, но только при наличии в непосредственной близости других транспортных средств", 10, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (25, " Включить левые указатели поворота, затем приступить к маневру", 11, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (26, "Убедиться, что Вас не обгоняют, затем включить левые указатели поворота и приступить к маневру", 11, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (27, " Только механическим транспортным средствам", 12, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (28, " Только маршрутным транспортным средствам", 12, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (29, "Любым транспортным средствам и пешеходам", 12, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (30, "Да", 13, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (31, " Да, но только при завершении обгона", 13, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (32, "Нет", 13, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (33, "Все автобусы", 14, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (34, "Автобусы, троллейбусы и трамваи, предназначенные для перевозки людей и движущиеся по установленному маршруту с обозначенными местами остановок", 14, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (35, "Любые транспортные средства, перевозящие пассажиров", 14, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (36, "Максимально допустимая для перевозки масса груза, установленная предприятием-изготовителем", 15, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (37, "Масса снаряженного транспортного средства без учета массы водителя, пассажиров и груза, установленная предприятием-изготовителем", 15, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (38, "Масса снаряженного транспортного средства с грузом, водителем и пассажирами, установленная предприятием-изготовителем в качестве максимально допустимой", 15, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (39, "Остановившись непосредственно перед пешеходным переходом, чтобы уступить дорогу пешеходу", 16, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (40, "Остановившись на проезжей части из-за технической неисправности автомобиля", 16, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (41, "В обоих перечисленных случаях", 16, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (42, " Видимость дороги, ограниченная рельефом местности, геометрическими параметрами дороги, растительностью, строениями, сооружениями или другими объектами", 17, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (43, "Видимость дороги менее 300 м в условиях тумана, дождя, снегопада, а также в сумерки", 17, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (44, "Видимость дороги менее 150 м в ночное время", 17, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (45, "Дефект проезжей части", 18, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (46, "Посторонний предмет", 18, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (47, "Неисправное или поврежденное транспортное средство", 18, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (48, " Транспортное средство, остановившееся на этой полосе из-за образования затора", 18, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (49, "Являются", 19, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (50, "Являются только обочины", 19, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (51, " Не являются", 19, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (52, " Опережение одного или нескольких транспортных средств, связанное с выездом из занимаемой полосы", 20, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (53, "Опережение одного или нескольких транспортных средств, связанное с выездом на полосу (сторону проезжей части), предназначенную для встречного движения, и последующим возвращением на ранее занимаемую полосу (сторону проезжей части)", 20, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (54, "Любое опережение одного или нескольких транспортных средств", 20, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (55, " Вы должны обязательно остановиться, чтобы пропустить других участников движения", 21, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (56, " Вы не должны возобновлять или продолжать движение, осуществлять какой-либо маневр, если это может вынудить других участников движения, имеющих по отношению к Вам преимущество, изменить направление движения или скорость", 21, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (57, "Вы должны остановиться только при наличии дорожного знака «Уступите дорогу»", 21, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (58, "Видимость дороги менее 100 м вблизи опасных поворотов и переломов продольного профиля дороги", 22, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (59, "Видимость дороги менее 300 м в условиях тумана, дождя, снегопада и т.п., а также в сумерки", 22, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (60, "Видимость дороги менее 150 м в ночное время", 22, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (61, " Дорога с твердым покрытием по отношению к грунтовой дороге", 23, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (62, "Дорога с тремя или более полосами движения по отношению к дороге с двумя полосами", 23, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (63, " Дорога с асфальтобетонным покрытием по отношению к дороге, покрытой брусчаткой", 23, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (64, "Только с места установки дорожного знака с названием населенного пункта на белом фоне", 24, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (65, "С места установки дорожного знака с названием населенного пункта на белом или синем фоне", 24, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (66, " В начале застроенной территории, непосредственно прилегающей к дороге", 24, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (67, "Установленные на переносной стойке", 25, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (68, " Имеющие желтый фон и установленные в местах производства дорожных работ", 25, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (69, " Все перечисленные", 25, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (70, "Предупреждает о приближении к стоп-линии перед регулируемым перекрестком", 26, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (71, "Предупреждает о приближении к стоп-линии и знаку «Движение без остановки запрещено»", 26, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (72, "Предупреждает о приближении к знаку «Уступите дорогу»", 26, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (73, "Требованиями линий разметки", 27, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (74, " Требованиями дорожных знаков", 27, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (75, "Правила эту ситуацию не регламентируют", 27, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (76, "Правила эту ситуацию не регламентируют", 28, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (77, "Необходимо руководствоваться белыми линиями", 28, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (78, "Необходимо руководствоваться оранжевыми линиями", 28, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (79, "Жёлтый", 29, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (80, "Оранжевый", 29, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (81, "Допускаются оба указанных цвета", 29, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (82, " Разрешается только при выезде из дворов и других прилегающих территорий", 30, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (83, "Разрешается только при обгоне", 30, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (84, "Разрешается только при интенсивном движении", 30, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (85, "Не разрешается", 30, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (86, "Предупреждает о неисправности светофора", 31, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (87, " Разрешает движение и информирует о том, что вскоре будет включен запрещающий сигнал", 31, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (88, "Запрещает дальнейшее движение", 31, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (89, "Разрешается", 32, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (90, "Разрешается, только если Вы намерены проехать перекресток в прямом направлении", 32, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (91, "Не разрешается", 32, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (92, "Не разрешается", 33, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (93, "Разрешается, только если Вы поворачиваете направо", 33, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (94, "Разрешается", 33, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (95, "Вы должны немедленно остановиться", 34, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (96, "Вы должны ускорить движение", 34, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (97, "Сигнал подается для привлечения внимания участников движения", 34, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (98, "Предупреждает о неисправности светофора", 35, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (99, "Разрешает движение и информирует о наличии нерегулируемого перекрестка или пешеходного перехода", 35, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (100, "Запрещает дальнейшее движение", 35, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (101, "Движение разрешается с особой осторожностью", 36, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (102, "Движение запрещено", 36, 1);
GO
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (103, "Светофорная сигнализация неисправна", 36, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (104, "Требованиями дорожных знаков", 37, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (105, "Значениями сигналов светофора", 37, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (106, "Указаниями регулировщика", 37, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (107, "Неисправна светофорная сигнализация", 38, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (108, "Вскоре будет включен зеленый сигнал", 38, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (109, "Вскоре будет включен красный сигнал", 38, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (110, "Предельные ограничения скорости, установленные для Вашего транспортного средства", 39, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (111, "Условия видимости", 39, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (112, "Только для остановки перед перекрестком или пешеходным переходом, когда после зеленого сигнала неожиданно для Вас включился желтый сигнал светофора", 40, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (113, "Только для предотвращения дорожно-транспортного происшествия", 40, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (114, " В обоих перечисленных случаях", 40, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (115, "Разрешается", 41, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (116, "Разрешается, если Вы не создадите помех другим транспортным средствам", 41, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (117, " Запрещается", 41, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (118, "Только при выполнении обгона", 42, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (119, "Только если установлены дорожные знаки, разрешающие движение со скоростью более 60 км/ч", 42, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (120, "В обоих перечисленных случаях", 42, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (121, "Предельные ограничения скорости, установленные для Вашего транспортного средства", 43, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (122, "Интенсивность движения", 43, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (123, "Только если полоса встречного движения свободна на достаточном для обгона расстоянии", 44, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (124, "Только если Вас никто не обгоняет", 44, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (125, "В случае, если выполнены оба условия", 44, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (126, "Он должен уступить дорогу автомобилю, завершающему обгон", 45, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (127, "Он не должен препятствовать обгону путем повышения скорости движения или иными действиями", 45, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (128, "Разрешен только на нерегулируемых перекрестках", 46, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (129, "Разрешен только на перекрестках неравнозначных дорог при движении по главной дороге", 46, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (130, "Запрещен во всех случаях", 46, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (131, "Обгон запрещен только на переезде", 47, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (132, "Обгон запрещен на переезде и на расстоянии 100 м до него", 47, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (133, "Обгон запрещен на переезде и на расстоянии 100 м до и после него", 47, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (134, "Разрешен", 48, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (135, "Запрещен", 48, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (136, "Запрещен", 49, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (137, "Запрещен только в конце подъема", 49, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (138, " Разрешен", 49, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (139, "Не запрещен", 50, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (140, "Запрещен", 50, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (141, "Да", 51, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (142, "Запрещен только при наличии на нем пешеходов", 51, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (143, "Не запрещен", 51, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (144, "Снизить скорость движения", 52, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (145, "Двигаться с прежней или большей скоростью", 52, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (146, "Двигаться с прежней или меньшей скоростью", 52, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (147, " Запрещен только под мостами, путепроводами и эстакадами", 53, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (148, "Запрещен", 53, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (149, "Разрешен", 53, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (150, "Только на хорошо просматриваемом месте на обочине", 54, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (151, "В любом месте на обочине", 54, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (152, "Только на предусмотренных для этого площадках или за пределами дороги", 54, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (153, "В любом из перечисленных мест", 54, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (154, "Знаков приоритета", 55, 1);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (155, "Запрещающих знаков", 55, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (156, " Предписывающих знаков", 55, 0);
INSERT INTO Answers (id, Name, QuestionId, Right) VALUES (157, "Всех перечисленных", 55, 0); 

INSERT INTO Persons (Id, LastName, FirstName, Patronymic) VALUES (1, "Иванов", "Иван", "Иванович")
 
INSERT INTO Questions (id, Name, Description, TestId) VALUES (4, "Когда Вы должны включить указатели поворота?", NULL, 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (5, "Когда может быть прекращена подача сигнала рукой о повороте?", NULL, 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (6, "Для обеспечения безопасности при выезде задним ходом с места стоянки, имеющего ограниченную видимость, необходимо:", NULL, 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (7, "Когда должна быть прекращена подача сигнала указателями поворота?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (8, "В каких местах водителю разрешается движение задним ходом?", NULL, 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (9, "Обязаны ли Вы подавать сигналы указателями поворота при начале движения в жилой зоне, обозначенной соответствующим знаком?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (10, "Должны ли Вы подавать сигналы указателями поворота при маневрировании на территории автостоянки или АЗС?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (11, "Как Вы должны действовать, если намереваетесь повернуть налево или выполнить разворот на двухполосной дороге?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (12, "Выезжая с прилегающей территории, Вы обязаны уступить дорогу:", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (13, "Дает ли Вам преимущество в движении подача сигнала указателями поворота?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (14, "Какие транспортные средства по Правилам относятся к маршрутным транспортным средствам?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (15, "Что называется разрешенной максимальной массой транспортного средства?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (16, "В каком случае Вы совершите вынужденную остановку?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (17, "Что означает термин «Ограниченная видимость»?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (18, "Какой неподвижный объект, не позволяющий продолжить движение по полосе, не относится к понятию «Препятствие»?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (19, "Являются ли тротуары и обочины частью дороги?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (20, "Что означает термин «обгон»?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (21, "Что означает требование уступить дорогу?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (22, "Что означает термин «Недостаточная видимость»?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (23, "Какая дорога является главной на перекрестке?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (24, "Где начинают действовать требования Правил, относящиеся к населенным пунктам?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (25, "Какие из предупреждающих и запрещающих знаков являются временными?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (26, "Что означает разметка в виде надписи «СТОП» на проезжей части?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (27, "Чем Вы должны руководствоваться, если значения дорожных знаков и линий горизонтальной разметки противоречат друг другу?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (28, "Чем Вы должны руководствоваться, если нанесенные на проезжей части белые и оранжевые линии разметки противоречат друг другу?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (29, "Какой цвет имеет временная горизонтальная разметка?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (30, "Разрешается ли Вам пересекать двойную сплошную линию продольной разметки?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (31, "Что означает мигание зеленого сигнала светофора?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (32, "Разрешается ли Вам продолжить движение, если при включении желтого сигнала светофора после зеленого Вы можете остановиться перед перекрестком, только применив экстренное торможение?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (33, "Разрешается ли Вам продолжить движение, если регулировщик поднял руку вверх после того, как Вы въехали на перекресток?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (34, "Какое значение имеет сигнал свистком, подаваемый регулировщиком?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (35, "Что означает мигание желтого сигнала светофора?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (36, "Красный мигающий сигнал или два попеременно мигающих красных сигнала светофора, установленного на железнодорожном переезде, означают:", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (37, "Чем Вы должны руководствоваться, если указания регулировщика противоречат сигналам светофора и значениям дорожных знаков?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (38, "Что означает сочетание красного и желтого сигналов светофора?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (39, "Что должно иметь для Вас решающее значение при выборе скорости движения в темное время суток?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (40, "В каком случае Вы можете прибегнуть к резкому торможению?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (41, "Разрешается ли Вам двигаться со слишком малой скоростью?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (42, "В каком случае Вы имеете право двигаться в населенном пункте со скоростью более 60 км/ч?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (43, "Что должно иметь для Вас решающее значение при выборе скорости движения в плотном потоке транспортных средств?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (44, "В каком случае Вы можете начать обгон, если такой маневр на данном участке дороги не запрещен?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (45, "Какие требования предъявляются к водителю обгоняемого транспортного средства?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (46, "Разрешен ли на двухполосной дороге обгон на перекрестках?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (47, "Какие ограничения, относящиеся к обгону, действуют на железнодорожных переездах и вблизи них?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (48, "Разрешен ли обгон на регулируемых перекрестках?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (49, "Разрешен ли обгон на подъеме?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (50, "Запрещен ли обгон в тоннелях?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (51, "Запрещен ли обгон на пешеходном переходе?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (52, "Водитель обгоняемого транспортного средства обязан:", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (53, "Запрещен ли обгон на мостах, путепроводах, эстакадах и под ними?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (54, "Где разрешается стоянка в целях длительного отдыха или ночлега на дорогах вне населенного пункта?", "", 1);
INSERT INTO Questions (id, Name, Description, TestId) VALUES (55, "Значения каких дорожных знаков отменяются сигналами светофора?", "", 1);
